#!/bin/bash -e
set -x
if [ "$(whoami)" == "root" ]; then
  SUDO_CMD=""
else
  SUDO_CMD="sudo"
fi

SDCARD_MOUNT=/tmp/sdcard
ROOTFS_DIR="${SDCARD_MOUNT}"

# Test if we have the SD card mounted
if [ ! -f "$SDCARD_MOUNT/etc/os-release" ]; then
  echo "ERROR: no SD card mounted, exit with error"
  exit 1
fi

# Use Debian apt repositories
cat << EOM | ${SUDO_CMD} chroot "${ROOTFS_DIR}" tee /etc/apt/sources.list.d/debian.list
deb http://httpredir.debian.org/debian jessie main
deb-src http://httpredir.debian.org/debian jessie main
EOM

# Configure network - use google nameserver's
cat << EOM | ${SUDO_CMD} chroot "${ROOTFS_DIR}" tee /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
EOM

## Install openssh-server, htop
#${SUDO_CMD} chroot "${ROOTFS_DIR}" apt-get update
#${SUDO_CMD} chroot "${ROOTFS_DIR}" apt-get install -y openssh-server htop

# Enable SSH root login
${SUDO_CMD} chroot "${ROOTFS_DIR}" sed -i 's|PermitRootLogin without-password|PermitRootLogin yes|g' /etc/ssh/sshd_config

# Configure network for eth0
# Set ethernet interface eth0 to dhcp
cat << EOM | ${SUDO_CMD} chroot "${ROOTFS_DIR}" tee /etc/systemd/network/eth0.network
[Match]
Name=eth0
[Network]
DHCP=yes
EOM

# Enable networkd
${SUDO_CMD} chroot "${ROOTFS_DIR}" systemctl enable systemd-networkd

